url: https://vistacodelab.com/

# Site settings
title: VistaCodeLab
email: hello@vistacodelab.com
description: "We create Web Apps, Android Apps, Hybrid Apps, Games, AI solutions and much more."

# Team names, titles and social links
people:
  - name: Rinoy R K
    pic: rinoy
    position: Software Engineer
    social:
      - title: globe
        url: https://rinoyrk.github.io/
      - title: facebook
        url: https://www.facebook.com/rinoy.rk.7
      - title: github
        url: https://github.com/rinoyrk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/vistacodelab
  - title: youtube-play
    url: https://www.youtube.com/@VistaCodeLab
  - title: linkedin
    url: https://www.linkedin.com/company/vistacodelab/
  - title: twitter
    url: https://twitter.com/vistacodelab/
  - title: whatsapp
    url: https://wa.me/916238461562

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
