url: http://vistacodelab.com/


# Site settings
title: VistaCodeLab
email: biz@vistacodelab.com
description: "We create Web Apps, Android Apps, React Native Apps, Games, Machine learning solutions and much more."


# Team names, titles and social links
people:
- name: Rinoy R K
  pic: rinoy
  position: Software Engineer
  social:
    - title: globe
      url: https://rinoyrk.github.io/
    - title: facebook
      url: https://www.facebook.com/rinoy.rk.7
    - title: github
      url: https://github.com/rinoyrk


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/vistacodelab
  - title: youtube-play
    url: https://www.youtube.com/channel/UC6MwW0pOqJ3oxmNRzVmgaIA

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty